# Acest workflow va instala dependențele Python, va rula teste și va verifica stilul de cod cu o versiune specifică de Python
# Pentru mai multe informații vezi: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Aplicație Python

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Verifică codul din repository
    - name: Setează Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instalează dependențele
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest matplotlib numpy  # Instalează dependențele necesare
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Verifică stilul de cod cu flake8
      run: |
        # Oprește build-ul dacă sunt erori de sintaxă Python sau nume nedefinite
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero tratează toate erorile ca și avertismente. Editorul GitHub are lățimea de 127 caractere
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
